---
kind: pipeline
type: kubernetes
name: spring-hell-world-drone

steps:
- name: Build
  image: maven:3-jdk-8
  commands:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
- name: Test
  image: maven:3-jdk-8
  commands:
  - mvn test -B
- name: code-analysis
  image: aosapps/drone-sonar-plugin
  settings:
    sonar_host:
      from_secret: sonar_host
    sonar_token:
      from_secret: sonar_token
  commands:
    - sonar-scanner -Dsonar.projectKey=${DRONE_REPO}
      -Dsonar.projectName=${DRONE_REPO}
      -Dsonar.host.url=$sonar_host
      -Dsonar.login=$sonar_token
      -Dsonar.tests=src/test/java
      -Dsonar.sources=src/main/java
      -Dsonar.java.libraries=./target/classes
      -Dsonar.java.binaries=./target/classes
