---
kind: pipeline
type: kubernetes
name: spring-hell-world-drone

steps:

- name: restore-cache
  image: plugins/s3-cache
  settings:
    pull: true
    endpoint: http://minio.default.svc:9000
    access_key: AKIAIOSFODNN7EXAMPLE
    secret_key: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    restore: true
    
- name: build
  image: maven:3-jdk-8
  commands:
  - mvn package -s settings.xml -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  
- name: rebuild-cache
  image: plugins/s3-cache
  settings:
    pull: true
    endpoint: http://minio.default.svc:9000
    access_key: AKIAIOSFODNN7EXAMPLE
    secret_key: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    rebuild: true
    mount:
      - '.m2'
    when:
      event: push
      
- name: test
  image: maven:3-jdk-8
  commands:
  - mvn test -B
      
- name: code-analysis
  image: aosapps/drone-sonar-plugin
  environment:
    sonar_host:
      from_secret: sonar_host
    sonar_token:
      from_secret: sonar_token
  commands:
    - sonar-scanner -Dsonar.projectKey=${DRONE_REPO}
      -Dsonar.projectName=${DRONE_REPO}
      -Dsonar.host.url=$sonar_host
      -Dsonar.login=$sonar_token
      -Dsonar.tests=src/test/java
      -Dsonar.sources=src/main/java
      -Dsonar.java.libraries=./target/classes
      -Dsonar.java.binaries=./target/classes
