---
kind: pipeline
type: kubernetes
name: spring-hell-world-drone

steps:
- name: Build
  image: maven:3-jdk-8
  commands:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
- name: Test
  image: maven:3-jdk-8
  commands:
  - mvn test -B
- name: code-analysis
  image: aosapps/drone-sonar-plugin
  settings:
    sonar_host:
      from_secret: sonar_host
    sonar_token:
      from_secret: sonar_token
